CREATE DATABASE EventPlus;
GO

CREATE TABLE TipoUsuario (
    IDTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Titulo NVARCHAR(100) NOT NULL

);
GO

CREATE TABLE TipoEvento (
    IDTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Titulo NVARCHAR(250) NOT NULL

);
GO

CREATE TABLE Instituicao (
    IDInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Nome NVARCHAR(50) NOT NULL,
    Endereco NVARCHAR(250),
    CNPJ NVARCHAR(14) NOT NULL UNIQUE 
);
GO

CREATE TABLE Usuario (
    IDUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Nome NVARCHAR(50) NOT NULL,
    Senha NVARCHAR(50) UNIQUE NOT NULL,
    Email NVARCHAR(250) NOT NULL,
    IDTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IDTipoUsuario)
);
GO



CREATE TABLE Evento (
    IDEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Nome NVARCHAR(250) NOT NULL,
    [Data] DATETIME NOT NULL,
    Descricao TEXT NOT NULL,
    IDTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento(IDTipoEvento),
    IDInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IDInstituicao)
);
GO


CREATE TABLE ComentarioEvento (
    IDComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    [Data] DATETIME NOT NULL,
    Exibe BIT NOT NULL,
    Descricao NVARCHAR(250),
    IDEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IDEvento),
);
GO

CREATE TABLE Presenca (
    IDPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Nome NVARCHAR(250),
    IDEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IDEvento),
    IDUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IDUsuario)
);
GO